# Generated by Django 3.2.9 on 2021-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='reciever',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='files',
            name='sender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Emailyňyz'),
        ),
        migrations.AlterField(
            model_name='reciever',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adyňyz'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adyňyz'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parolyňyz'),
        ),
    ]
